from __future__ import annotations

# Ethiopian Orthodox canon (81 books) English display names by numeric index.
BOOKS_EN: dict[int, str] = {
    1: 'Genesis',
    2: 'Exodus',
    3: 'Leviticus',
    4: 'Numbers',
    5: 'Deuteronomy',
    6: 'Joshua',
    7: 'Judges',
    8: 'Ruth',
    9: '1 Samuel',
    10: '2 Samuel',
    11: '1 Kings',
    12: '2 Kings',
    13: '1 Chronicles',
    14: '2 Chronicles',
    15: 'Jubilees',
    16: '1 Enoch',
    17: 'Ezra',
    18: 'Nehemiah',
    19: "Rest of Ezra (Sutu'el)",
    20: '2 Ezra (Ezra Kal’e)',
    21: 'Tobit',
    22: 'Judith',
    23: 'Esther (long)',
    24: '1 Meqabyan',
    25: '2 Meqabyan',
    26: '3 Meqabyan',
    27: 'Job',
    28: 'Psalms',
    29: 'Proverbs',
    30: 'Reproof (Tegesats)',
    31: 'Wisdom of Solomon',
    32: 'Ecclesiastes',
    33: 'Song of Songs',
    34: 'Sirach (Ecclesiasticus)',
    35: 'Isaiah',
    36: 'Jeremiah',
    37: 'Lamentations of Jeremiah',
    38: 'Rest of Jeremiah (incl. 4 Baruch)',
    39: 'Baruch',
    40: 'Rest of Baruch (Letter of Jeremiah)',
    41: 'Ezekiel',
    42: 'Daniel',
    43: 'Hosea',
    44: 'Amos',
    45: 'Micah',
    46: 'Joel',
    47: 'Obadiah',
    48: 'Jonah',
    49: 'Nahum',
    50: 'Habakkuk',
    51: 'Zephaniah',
    52: 'Haggai',
    53: 'Zechariah',
    54: 'Malachi',
    55: 'Gospel of Matthew',
    56: 'Gospel of Mark',
    57: 'Gospel of Luke',
    58: 'Gospel of John',
    59: 'Acts',
    60: 'Romans',
    61: '1 Corinthians',
    62: '2 Corinthians',
    63: 'Galatians',
    64: 'Ephesians',
    65: 'Philippians',
    66: 'Colossians',
    67: '1 Thessalonians',
    68: '2 Thessalonians',
    69: '1 Timothy',
    70: '2 Timothy',
    71: 'Titus',
    72: 'Philemon',
    73: 'Hebrews',
    74: '1 Peter',
    75: '2 Peter',
    76: '1 John',
    77: '2 John',
    78: '3 John',
    79: 'James',
    80: 'Jude',
    81: 'Revelation',
}
