#!/usr/bin/env python3
"""Inventory defects in the Amharic source text.

Emits markdown. Run it rather than hand-maintaining a list, so the record cannot
drift from the data:

    python tools/audit_source.py > SOURCE_ISSUES.md
"""

from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'src'))

from ebible.data.store import DB_PATH  # noqa: E402

# Verse N whose text opens with the numeral N+1: the following verse's marker
# survived inline while the verse itself did not.
LOST_VERSE_RE = re.compile(r'^(\d+)')
FOOTNOTE_RE = re.compile(r'(?<=[ሀ-፿])\d+')

# The same defect can land mid-verse rather than at the start, when the dropped
# verse followed a sentence that ended cleanly: '…የላቸውምና።11 አቤቱ…'. Those look
# exactly like footnote markers to FOOTNOTE_RE, and were miscounted as such until
# Judith 7:10 and Jeremiah 22:27 turned up. The tell is the value: a stranded
# verse number equals verse+1, while footnote markers ascend through the canon
# independently of any verse number.
INLINE_DIGIT_RE = re.compile(r'(?<=[ሀ-፿])(\d+)')
LATIN_RE = re.compile(r'[ሀ-፿][A-Za-z]|[A-Za-z][ሀ-፿]')


def main() -> int:
    db = sqlite3.connect(f'file:{DB_PATH}?mode=ro', uri=True)
    db.row_factory = sqlite3.Row
    rows = db.execute(
        'SELECT b.name_en, b.slug, v.chapter, v.verse, v.text_am'
        ' FROM verse v JOIN book b ON b.id = v.book_id ORDER BY v.id'
    ).fetchall()
    total = len(rows)

    lost, footnotes, latin, trailing = [], [], [], []
    for r in rows:
        txt = r['text_am']
        ref = f'{r["name_en"]} {r["chapter"]}:{r["verse"]}'
        m = LOST_VERSE_RE.match(txt)
        inline = INLINE_DIGIT_RE.search(txt)
        stranded = inline and int(inline.group(1)) == r['verse'] + 1
        if (m and int(m.group(1)) == r['verse'] + 1) or stranded:
            lost.append((ref, txt[:60]))
        elif inline:
            footnotes.append((ref, inline.group(0), txt[:50]))
        if LATIN_RE.search(txt):
            latin.append((ref, txt[:60]))
        if re.search(r'።[ሀ-፿]$', txt):
            trailing.append((ref, txt[-22:]))

    affected = len({*(r for r, *_ in lost), *(r for r, *_ in footnotes),
                    *(r for r, *_ in latin), *(r for r, *_ in trailing)})

    print('# Source issues\n')
    print('Defects in `assets/Bible81`, the scraped Amharic text. Generated by')
    print('`tools/audit_source.py` — do not edit by hand.\n')
    print(f'{affected} of {total:,} verses affected ({affected / total * 100:.2f}%).\n')
    print('None of these were introduced by this project. They are recorded rather')
    print('than repaired by guesswork: where content is missing, it stays missing and')
    print('flagged. Inventing plausible scripture to fill a hole would be worse than')
    print('the hole.\n')

    print('## 1. Lost verses — SERIOUS, unrepairable here\n')
    print(f'**{len(lost)} verses are absent from the source.**\n')
    print('The scrape dropped a verse and left the *following* verse\'s number stranded')
    print('inline, shifting the rest of the chapter up by one. Exodus 4 is the clearest')
    print('case: verse 3 ends with the staff becoming a serpent, verse 4 opens with "the')
    print('God of their fathers", and the verse between them — "put out your hand and')
    print('take it by the tail" — is simply gone. That chapter holds 30 verses where it')
    print('should hold 31.\n')
    print('Fixing this needs the original source or a second Amharic edition. It cannot')
    print('be reconstructed from what is here.\n')
    print('| Reference | Text begins |')
    print('|---|---|')
    for ref, txt in lost:
        print(f'| {ref} | `{txt}…` |')

    print('\n## 2. Footnote digits — repaired at build time\n')
    print(f'{len(footnotes)} verses carry superscript footnote markers welded into words')
    print('(`አቤል2ን` = Abel, `አብርሃም26` = Abraham). The values ascend through the canon,')
    print('which is what identifies them as markers: Amharic writes numbers as Ge\'ez')
    print('numerals or spells them out, never as ASCII digits mid-word.\n')
    print('`tools/build_db.py` strips these during the build; `assets/` stays untouched.\n')
    print('| Reference | Marker | Context |')
    print('|---|---|---|')
    for ref, digit, txt in footnotes[:20]:
        print(f'| {ref} | `{digit}` | `{txt}…` |')
    if len(footnotes) > 20:
        print(f'\n…and {len(footnotes) - 20} more.\n')

    print('\n## 3. Latin letters spliced into Ge\'ez — unrepairable here\n')
    print(f'{len(latin)} verses contain Latin characters inside Ge\'ez words. A character')
    print('was *replaced*, not merely inserted, so the original letter is unrecoverable')
    print('from this file. Left untouched.\n')
    print('| Reference | Text |')
    print('|---|---|')
    for ref, txt in latin:
        print(f'| {ref} | `{txt}…` |')

    print('\n## 4. Absorbed editorial apparatus\n')
    gloss = [
        (f'{r["name_en"]} {r["chapter"]}:{r["verse"]}', r['text_am'][:90])
        for r in rows
        if r['text_am'].count('(') != r['text_am'].count(')')
    ]
    print(f'{len(gloss)} verse(s) are not scripture but a lexicographer\'s note that was')
    print('absorbed into the verse numbering, adding a verse and shifting the rest of')
    print('the chapter.\n')
    print('Unbalanced parentheses are what distinguish these from the many *legitimate*')
    print('in-text glosses ("Rabbi, which means Teacher" at John 1:39; "Tabitha, which')
    print('means Dorcas" at Acts 9:36) — those are scripture and must not be stripped.\n')
    print('| Reference | Text |')
    print('|---|---|')
    for ref, txt in gloss:
        print(f'| {ref} | `{txt}…` |')
    print('\nLeft in place: removing it would renumber the chapter, and the numbering is')
    print('what the translation is aligned to.\n')

    print('\n## 5. Stray trailing letters — cosmetic\n')
    print(f'{len(trailing)} verses end with a lone letter after the full stop `።`,')
    print('most often `ፕ` or `ች`. Harmless to reading; left as-is.\n')
    print('| Reference | Ends |')
    print('|---|---|')
    for ref, txt in trailing:
        print(f'| {ref} | `…{txt}` |')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
