#!/data/data/com.termux/files/usr/bin/sh
# ebible on Termux.
#
# The reader is fully offline: no translate-shell, no proot bind, no network.
# Everything it needs is compiled into the package.
set -e
exec python -m ebible "$@"
